stages:
  - build
  - test
  - push
  - deploy

variables:
  DOCKERFILE_PATH: ./docker
  API_SRC_PATH: ./
  #AWS
  PROJECT_NAME: erp-api
  AWS_REGISTRY_URL: 009795078640.dkr.ecr.ap-southeast-1.amazonaws.com

api.build:
  stage: build
  before_script:
    - aws ecr get-login-password --region ap-southeast-1 | docker login  --username AWS  --password-stdin 009795078640.dkr.ecr.ap-southeast-1.amazonaws.com
    - >
      if git diff HEAD~ --name-only | grep -i 'docker\|runtime.Dockerfile'; then
        docker build -f $DOCKERFILE_PATH/runtime.Dockerfile -t $AWS_REGISTRY_URL/$PROJECT_NAME:runtime $API_SRC_PATH
        docker push $AWS_REGISTRY_URL/$PROJECT_NAME:runtime
      fi;
  script:
    - docker build --cache-from $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG -f $DOCKERFILE_PATH/staging.Dockerfile -t $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA $API_SRC_PATH
    - docker push $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  only:
    - develop
    - release
    - tags

api.push.staging:
  stage: push
  variables:
    GIT_STRATEGY: none
  dependencies:
    - api.build
  script:
    - docker pull $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
    - docker tag $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - docker push $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - docker rmi $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  only:
    - develop
    - release

api.deploy.staging:
  stage: deploy
  dependencies:
    - api.push.staging
  script:
    - docker pull $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - cd deployment && docker-compose down && docker-compose -f docker-compose.staging.yml up -d
  only:
    - develop

api.push.tag:
  stage: push
  variables:
    GIT_STRATEGY: none
  dependencies:
    - api.build
  script:
    - docker pull $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
    - docker tag $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_TAG
    - docker push $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_TAG
    - docker rmi $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  only:
    - tags
