//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AccountResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ERPSystem.Common.Resources.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string msgChangePassSuccess {
            get {
                return ResourceManager.GetString("msgChangePassSuccess", resourceCulture);
            }
        }
        
        public static string msgWrongPassword {
            get {
                return ResourceManager.GetString("msgWrongPassword", resourceCulture);
            }
        }
        
        public static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        public static string lblConfirmNewPassword {
            get {
                return ResourceManager.GetString("lblConfirmNewPassword", resourceCulture);
            }
        }
        
        public static string lblToken {
            get {
                return ResourceManager.GetString("lblToken", resourceCulture);
            }
        }
        
        public static string lblPrimaryManager {
            get {
                return ResourceManager.GetString("lblPrimaryManager", resourceCulture);
            }
        }
        
        public static string lblDynamic {
            get {
                return ResourceManager.GetString("lblDynamic", resourceCulture);
            }
        }
        public static string lblAccount {
            get {
                return ResourceManager.GetString("lblAccount", resourceCulture);
            }
        }
        public static string msgInvalidAccount {
            get {
                return ResourceManager.GetString("msgInvalidAccount", resourceCulture);
            }
        }
        public static string msgEmptyAvatar {
            get {
                return ResourceManager.GetString("msgEmptyAvatar", resourceCulture);
            }
        }
         public static string msgInvalidUser {
            get {
                return ResourceManager.GetString("msgInvalidUser", resourceCulture);
            }
        }
    }
}
