//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public CategoryResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ERPSystem.Common.Resources.CategoryResource", typeof(CategoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lblSchedule {
            get {
                return ResourceManager.GetString("lblSchedule", resourceCulture);
            }
        }
        
        public static string lblHoliday {
            get {
                return ResourceManager.GetString("lblHoliday", resourceCulture);
            }
        }
        
        public static string msgNameExisted {
            get {
                return ResourceManager.GetString("msgNameExisted", resourceCulture);
            }
        }
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        public static string OutSide {
            get {
                return ResourceManager.GetString("OutSide", resourceCulture);
            }
        }
        public static string BussinessTrip {
            get {
                return ResourceManager.GetString("BussinessTrip", resourceCulture);
            }
        }
        public static string DayOff {
            get {
                return ResourceManager.GetString("DayOff", resourceCulture);
            }
        }
        public static string Cooperation {
            get {
                return ResourceManager.GetString("Cooperation", resourceCulture);
            }
        }
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        public static string msgColorExisted {
            get {
                return ResourceManager.GetString("msgColorExisted", resourceCulture);
            }
        }
    }
}
