//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MessageResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ERPSystem.Common.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        public static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        public static string UnprocessableEntity {
            get {
                return ResourceManager.GetString("UnprocessableEntity", resourceCulture);
            }
        }
        
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        public static string AnUnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        public static string ExpiredTokenAndRefreshTokenMismatched {
            get {
                return ResourceManager.GetString("ExpiredTokenAndRefreshTokenMismatched", resourceCulture);
            }
        }
        
        public static string ExpiredToken {
            get {
                return ResourceManager.GetString("ExpiredToken", resourceCulture);
            }
        }
        
        public static string msgCreateNewFailed {
            get {
                return ResourceManager.GetString("msgCreateNewFailed", resourceCulture);
            }
        }
        
        public static string msgCreateNewSuccess {
            get {
                return ResourceManager.GetString("msgCreateNewSuccess", resourceCulture);
            }
        }
        
        public static string msgUpdateSuccess {
            get {
                return ResourceManager.GetString("msgUpdateSuccess", resourceCulture);
            }
        }
        
        public static string msgUpdateFailed {
            get {
                return ResourceManager.GetString("msgUpdateFailed", resourceCulture);
            }
        }
        
        public static string msgDeleteSuccess {
            get {
                return ResourceManager.GetString("msgDeleteSuccess", resourceCulture);
            }
        }
        
        public static string msgDeleteFailed {
            get {
                return ResourceManager.GetString("msgDeleteFailed", resourceCulture);
            }
        }
        
        public static string msgNotFoundRole {
            get {
                return ResourceManager.GetString("msgNotFoundRole", resourceCulture);
            }
        }
        
        public static string msgDuplicatedData {
            get {
                return ResourceManager.GetString("msgDuplicatedData", resourceCulture);
            }
        }
        
        public static string MessageAddSuccess {
            get {
                return ResourceManager.GetString("MessageAddSuccess", resourceCulture);
            }
        }
        
        public static string InvalidRoleUpdate {
            get {
                return ResourceManager.GetString("InvalidRoleUpdate", resourceCulture);
            }
        }
        
        public static string MessageUpdateSuccess {
            get {
                return ResourceManager.GetString("MessageUpdateSuccess", resourceCulture);
            }
        }
        
        public static string msgFailedDeleteBasicRole {
            get {
                return ResourceManager.GetString("msgFailedDeleteBasicRole", resourceCulture);
            }
        }
        
        public static string msgFailedDeleteRole {
            get {
                return ResourceManager.GetString("msgFailedDeleteRole", resourceCulture);
            }
        }
        
        public static string MessageDeleteSuccess {
            get {
                return ResourceManager.GetString("MessageDeleteSuccess", resourceCulture);
            }
        }
        
        public static string MessageSuccess {
            get {
                return ResourceManager.GetString("MessageSuccess", resourceCulture);
            }
        }
        public static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        public static string NotEmptyValidator {
            get {
                return ResourceManager.GetString("NotEmptyValidator", resourceCulture);
            }
        }
        public static string InvalidInformation {
            get {
                return ResourceManager.GetString("InvalidInformation", resourceCulture);
            }
        }
        public static string EmailDoestNotExist {
            get {
                return ResourceManager.GetString("EmailDoestNotExist", resourceCulture);
            }
        }
        public static string MessageResetPassSuccess {
            get {
                return ResourceManager.GetString("MessageResetPassSuccess", resourceCulture);
            }
        }
        public static string NullFrontEndURL {
            get {
                return ResourceManager.GetString("NullFrontEndURL", resourceCulture);
            }
        }
        public static string MessageEmailNotRegister {
            get {
                return ResourceManager.GetString("MessageEmailNotRegister", resourceCulture);
            }
        }
        public static string MessageSendEmailSuccess {
            get {
                return ResourceManager.GetString("MessageSendEmailSuccess", resourceCulture);
            }
        }
    }
}
