//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissionResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public PermissionResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ERPSystem.Common.Resources.PermissionResource", typeof(PermissionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        public static string ViewUser {
            get {
                return ResourceManager.GetString("ViewUser", resourceCulture);
            }
        }
        
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        public static string DescriptionAddUser {
            get {
                return ResourceManager.GetString("DescriptionAddUser", resourceCulture);
            }
        }
        public static string DescriptionEditUser {
            get {
                return ResourceManager.GetString("DescriptionEditUser", resourceCulture);
            }
        }
        public static string DescriptionDeleteUser {
            get {
                return ResourceManager.GetString("DescriptionDeleteUser", resourceCulture);
            }
        }
        
        public static string DescriptionViewUser {
            get {
                return ResourceManager.GetString("DescriptionViewUser", resourceCulture);
            }
        }
        
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        public static string ViewCategory {
            get {
                return ResourceManager.GetString("ViewCategory", resourceCulture);
            }
        }
        
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        public static string DescriptionViewCategory {
            get {
                return ResourceManager.GetString("DescriptionViewCategory", resourceCulture);
            }
        }
        
        public static string DescriptionAddCategory {
            get {
                return ResourceManager.GetString("DescriptionAddCategory", resourceCulture);
            }
        }
        
        public static string DescriptionEditCategory {
            get {
                return ResourceManager.GetString("DescriptionEditCategory", resourceCulture);
            }
        }
        
        public static string DescriptionDeleteCategory {
            get {
                return ResourceManager.GetString("DescriptionDeleteCategory", resourceCulture);
            }
        }
        
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        public static string ViewDepartment {
            get {
                return ResourceManager.GetString("ViewDepartment", resourceCulture);
            }
        }
        
        public static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        public static string EditDepartment {
            get {
                return ResourceManager.GetString("EditDepartment", resourceCulture);
            }
        }
        
        public static string DeleteDepartment {
            get {
                return ResourceManager.GetString("DeleteDepartment", resourceCulture);
            }
        }
        
        public static string ExportDepartment {
            get {
                return ResourceManager.GetString("ExportDepartment", resourceCulture);
            }
        }
        
        public static string DescriptionViewDepartment {
            get {
                return ResourceManager.GetString("DescriptionViewDepartment", resourceCulture);
            }
        }
        
        public static string DescriptionAddDepartment {
            get {
                return ResourceManager.GetString("DescriptionAddDepartment", resourceCulture);
            }
        }
        
        public static string DescriptionEditDepartment {
            get {
                return ResourceManager.GetString("DescriptionEditDepartment", resourceCulture);
            }
        }
        
        public static string DescriptionDeleteDepartment {
            get {
                return ResourceManager.GetString("DescriptionDeleteDepartment", resourceCulture);
            }
        }
        
        public static string DescriptionExportDepartment {
            get {
                return ResourceManager.GetString("DescriptionExportDepartment", resourceCulture);
            }
        }
        
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        public static string ViewSupplier {
            get {
                return ResourceManager.GetString("ViewSupplier", resourceCulture);
            }
        }
        
        public static string AddSupplier {
            get {
                return ResourceManager.GetString("AddSupplier", resourceCulture);
            }
        }
        public static string EditSupplier {
            get {
                return ResourceManager.GetString("EditSupplier", resourceCulture);
            }
        }
        
        public static string DeleteSupplier {
            get {
                return ResourceManager.GetString("DeleteSupplier", resourceCulture);
            }
        }
        
        public static string DescriptionAddSupplier {
            get {
                return ResourceManager.GetString("DescriptionAddSupplier", resourceCulture);
            }
        }
        public static string DescriptionEditSupplier {
            get {
                return ResourceManager.GetString("DescriptionEditSupplier", resourceCulture);
            }
        }
        public static string DescriptionDeleteSupplier {
            get {
                return ResourceManager.GetString("DescriptionDeleteSupplier", resourceCulture);
            }
        }
        
        public static string DescriptionViewSupplier {
            get {
                return ResourceManager.GetString("DescriptionViewSupplier", resourceCulture);
            }
        }
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        public static string ViewPurchase {
            get {
                return ResourceManager.GetString("ViewPurchase", resourceCulture);
            }
        }
        
        public static string AddPurchase {
            get {
                return ResourceManager.GetString("AddPurchase", resourceCulture);
            }
        }
        public static string EditPurchase {
            get {
                return ResourceManager.GetString("EditPurchase", resourceCulture);
            }
        }
        
        public static string DeletePurchase {
            get {
                return ResourceManager.GetString("DeletePurchase", resourceCulture);
            }
        }
        
        public static string DescriptionAddPurchase {
            get {
                return ResourceManager.GetString("DescriptionAddPurchase", resourceCulture);
            }
        }
        public static string DescriptionEditPurchase {
            get {
                return ResourceManager.GetString("DescriptionEditPurchase", resourceCulture);
            }
        }
        public static string DescriptionDeletePurchase {
            get {
                return ResourceManager.GetString("DescriptionDeletePurchase", resourceCulture);
            }
        }
        
        public static string DescriptionViewPurchase {
            get {
                return ResourceManager.GetString("DescriptionViewPurchase", resourceCulture);
            }
        }
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        public static string ViewSetting {
            get {
                return ResourceManager.GetString("ViewSetting", resourceCulture);
            }
        }
        
        public static string AddSetting {
            get {
                return ResourceManager.GetString("AddSetting", resourceCulture);
            }
        }
        public static string EditSetting {
            get {
                return ResourceManager.GetString("EditSetting", resourceCulture);
            }
        }
        
        public static string DeleteSetting {
            get {
                return ResourceManager.GetString("DeleteSetting", resourceCulture);
            }
        }
        
        public static string DescriptionAddSetting {
            get {
                return ResourceManager.GetString("DescriptionAddSetting", resourceCulture);
            }
        }
        public static string DescriptionEditSetting {
            get {
                return ResourceManager.GetString("DescriptionEditSetting", resourceCulture);
            }
        }
        public static string DescriptionDeleteSetting {
            get {
                return ResourceManager.GetString("DescriptionDeleteSetting", resourceCulture);
            }
        }
        
        public static string DescriptionViewSetting {
            get {
                return ResourceManager.GetString("DescriptionViewSetting", resourceCulture);
            }
        }
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        public static string ViewRole {
            get {
                return ResourceManager.GetString("ViewRole", resourceCulture);
            }
        }
        
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        public static string DescriptionAddRole {
            get {
                return ResourceManager.GetString("DescriptionAddRole", resourceCulture);
            }
        }
        public static string DescriptionEditRole {
            get {
                return ResourceManager.GetString("DescriptionEditRole", resourceCulture);
            }
        }
        public static string DescriptionDeleteRole {
            get {
                return ResourceManager.GetString("DescriptionDeleteRole", resourceCulture);
            }
        }
        
        public static string DescriptionViewRole {
            get {
                return ResourceManager.GetString("DescriptionViewRole", resourceCulture);
            }
        }
        public static string DailyReport {
            get {
                return ResourceManager.GetString("DailyReport", resourceCulture);
            }
        }
        
        public static string ViewDailyReport {
            get {
                return ResourceManager.GetString("ViewDailyReport", resourceCulture);
            }
        }
        
        public static string AddDailyReport {
            get {
                return ResourceManager.GetString("AddDailyReport", resourceCulture);
            }
        }
        public static string EditDailyReport {
            get {
                return ResourceManager.GetString("EditDailyReport", resourceCulture);
            }
        }
        
        public static string DeleteDailyReport {
            get {
                return ResourceManager.GetString("DeleteDailyReport", resourceCulture);
            }
        }
        
        public static string DescriptionAddDailyReport {
            get {
                return ResourceManager.GetString("DescriptionAddDailyReport", resourceCulture);
            }
        }
        public static string DescriptionEditDailyReport {
            get {
                return ResourceManager.GetString("DescriptionEditDailyReport", resourceCulture);
            }
        }
        public static string DescriptionDeleteDailyReport {
            get {
                return ResourceManager.GetString("DescriptionDeleteDailyReport", resourceCulture);
            }
        }
        
        public static string DescriptionViewDailyReport {
            get {
                return ResourceManager.GetString("DescriptionViewDailyReport", resourceCulture);
            }
        }
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        public static string ViewFolder {
            get {
                return ResourceManager.GetString("ViewFolder", resourceCulture);
            }
        }
        
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        public static string EditFolder {
            get {
                return ResourceManager.GetString("EditFolder", resourceCulture);
            }
        }
        
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        public static string DescriptionAddFolder {
            get {
                return ResourceManager.GetString("DescriptionAddFolder", resourceCulture);
            }
        }
        public static string DescriptionEditFolder {
            get {
                return ResourceManager.GetString("DescriptionEditFolder", resourceCulture);
            }
        }
        public static string DescriptionDeleteFolder {
            get {
                return ResourceManager.GetString("DescriptionDeleteFolder", resourceCulture);
            }
        }
        
        public static string DescriptionViewFolder {
            get {
                return ResourceManager.GetString("DescriptionViewFolder", resourceCulture);
            }
        }
        public static string Meeting {
            get {
                return ResourceManager.GetString("Meeting", resourceCulture);
            }
        }
        
        public static string ViewMeeting {
            get {
                return ResourceManager.GetString("ViewMeeting", resourceCulture);
            }
        }
        
        public static string AddMeeting {
            get {
                return ResourceManager.GetString("AddMeeting", resourceCulture);
            }
        }
        public static string EditMeeting {
            get {
                return ResourceManager.GetString("EditMeeting", resourceCulture);
            }
        }
        
        public static string DeleteMeeting {
            get {
                return ResourceManager.GetString("DeleteMeeting", resourceCulture);
            }
        }
        
        public static string DescriptionAddMeeting {
            get {
                return ResourceManager.GetString("DescriptionAddMeeting", resourceCulture);
            }
        }
        public static string DescriptionEditMeeting {
            get {
                return ResourceManager.GetString("DescriptionEditMeeting", resourceCulture);
            }
        }
        public static string DescriptionDeleteMeeting {
            get {
                return ResourceManager.GetString("DescriptionDeleteMeeting", resourceCulture);
            }
        }
        
        public static string DescriptionViewMeeting {
            get {
                return ResourceManager.GetString("DescriptionViewMeeting", resourceCulture);
            }
        }
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        public static string ViewSchedule {
            get {
                return ResourceManager.GetString("ViewSchedule", resourceCulture);
            }
        }
        
        public static string AddSchedule {
            get {
                return ResourceManager.GetString("AddSchedule", resourceCulture);
            }
        }
        public static string EditSchedule {
            get {
                return ResourceManager.GetString("EditSchedule", resourceCulture);
            }
        }
        
        public static string DeleteSchedule {
            get {
                return ResourceManager.GetString("DeleteSchedule", resourceCulture);
            }
        }
        
        public static string DescriptionAddSchedule {
            get {
                return ResourceManager.GetString("DescriptionAddSchedule", resourceCulture);
            }
        }
        public static string DescriptionEditSchedule {
            get {
                return ResourceManager.GetString("DescriptionEditSchedule", resourceCulture);
            }
        }
        public static string DescriptionDeleteSchedule {
            get {
                return ResourceManager.GetString("DescriptionDeleteSchedule", resourceCulture);
            }
        }
        
        public static string DescriptionViewSchedule {
            get {
                return ResourceManager.GetString("DescriptionViewSchedule", resourceCulture);
            }
        }
        public static string WorkLog {
            get {
                return ResourceManager.GetString("WorkLog", resourceCulture);
            }
        }
        
        public static string ViewWorkLog {
            get {
                return ResourceManager.GetString("ViewWorkLog", resourceCulture);
            }
        }
        
        public static string AddWorkLog {
            get {
                return ResourceManager.GetString("AddWorkLog", resourceCulture);
            }
        }
        public static string EditWorkLog {
            get {
                return ResourceManager.GetString("EditWorkLog", resourceCulture);
            }
        }
        
        public static string DeleteWorkLog {
            get {
                return ResourceManager.GetString("DeleteWorkLog", resourceCulture);
            }
        }
        
        public static string DescriptionAddWorkLog {
            get {
                return ResourceManager.GetString("DescriptionAddWorkLog", resourceCulture);
            }
        }
        public static string DescriptionEditWorkLog {
            get {
                return ResourceManager.GetString("DescriptionEditWorkLog", resourceCulture);
            }
        }
        public static string DescriptionDeleteWorkLog {
            get {
                return ResourceManager.GetString("DescriptionDeleteWorkLog", resourceCulture);
            }
        }
        
        public static string DescriptionViewWorkLog {
            get {
                return ResourceManager.GetString("DescriptionViewWorkLog", resourceCulture);
            }
        }
    }
}
