version: '2.4'

x-default: &default
  networks:
    - dmpw-net
  restart: always

services:
  erp-api:
    << : *default
    image: 009795078640.dkr.ecr.ap-southeast-1.amazonaws.com/erp-api:develop
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
    volumes:
      - ./settings.erp-api.json:/tmp/appsettings.Local.json  
    entrypoint: /bin/bash -c 'cp /tmp/appsettings.Local.json /app/appsettings.Local.json && dotnet ERPSystem.Api.dll'
    ports:
      - "5000:5000"
networks:
  dmpw-net:
